apiVersion: apps/v1 #1
kind: Deployment #2
metadata: #3
  name: nodejs-deployment #4
spec: #5
  replicas: 2 #6
  selector: #7
    matchLabels: #7
      app: nodejs #7
  template: #8
    metadata: #9
      labels: #10
        app: nodejs #11
    spec: #12
      containers: #13
      - name: nodongo #14
        image: kavanas/team_4 #15
        ports: #16
        - containerPort: 3000 #17
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"